FROM python:3.10


RUN apt-get update && apt-get -y upgrade

RUN apt-get install -y wkhtmltopdf && apt-get install -y xvfb

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

EXPOSE 8000

WORKDIR /cmc_pr
COPY requirements_prod.txt /cmc_pr
RUN pip install -r /cmc_pr/requirements_prod.txt

COPY . /cmc_pr

RUN chmod +x ./docker-web-cmc-entrypoint.sh
RUN chmod +x ./wait-for-it.sh



#RUN adduser --disabled-password cmc-user
#
#USER cmc-user
