version: '3.1'

services:

  postgres:
    container_name: postgres
    image: postgres:15.1
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379" # убрать когда будет все докирезировано

  worker:
    build:
      context: .
    image: cmc_celery:latest
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - .:/cmc
    labels:
      - redis
    depends_on:
      - redis
    environment:
      - DB_HOST=postgres
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}


  flower:
    build:
      context: .
    image: cmc_flower:latest
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
#    command: --broker=redis://redis:6379/0 flower && -A celery_app.app flower
    volumes:
      - .:/cmc
    labels:
      - redis
      - worker
    depends_on:
      - redis
      - worker
    ports:
      - "5555:5555"


volumes:
  postgres_data:
    driver: local
