version: '3.1'

services:
  web_cmc:
    image: cmc:v1
    environment:
      - DB_HOST=postgres
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
    ports:
      - "8000:8000"
    volumes:
      - .:/cmc
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
       - postgres
       - redis

  postgres:
    container_name: postgres
    image: postgres:15.1
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    ports:
      - "3333:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    links:
      - postgres
    depends_on:
      - postgres


  redis:
    image: redis:latest
    hostname: cache_redis
    restart: unless-stopped


  worker:
    image: cmc:v1
    restart: unless-stopped
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - .:/cmc
    links:
      - redis
    depends_on:
      - redis
    environment:
      - DB_HOST=postgres
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}

  worker2:
    image: cmc:v1
    restart: unless-stopped
    hostname: worker2
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - .:/cmc
    links:
      - redis
    depends_on:
      - redis
    environment:
      - DB_HOST=postgres
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}

  celery-beat:
    image: cmc:v1
    restart: unless-stopped
    hostname: worker2
    entrypoint: celery
    command: -A celery_app.app beat --loglevel=info
    volumes:
      - .:/cmc
    links:
      - redis
    depends_on:
      - redis
    environment:
      - DB_HOST=postgres
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}


  flower:
    image: cmc:v1
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - .:/cmc
    links:
      - redis
      - worker
    depends_on:
      - redis
      - worker
    ports:
      - "5555:5555"

volumes:
  postgres_data:
    driver: local