version: '3.1'

services:
  postgres:
    container_name: postgres
    image: postgres:15.1
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  cache:
    image: redis:latest
    hostname: redis
    restart: always
    ports:
      - "6379:6379" # убрать когда будет все докирезировано
#    expose:
#      - 6379
    volumes:
      - ./data/cache:/data

volumes:
  postgres_data:
    driver: local
