version: '3.1'

x-function: &function
  build:
    context: .
  image: cmc:v3
  volumes:
    - .:/cmc
  restart: unless-stopped
  environment:
    - DJANGO_SETTINGS_MODULE=core.settings.dev
    - DB_HOST=postgres
    - DB_USER=${POSTGRES_USER}
    - DB_PASSWORD=${POSTGRES_PASSWORD}
    - DB_NAME=${POSTGRES_DB}
  networks:
    - cmc_network


services:
  postgres:
    container_name: postgres
    image: postgres:15.1
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    networks:
      - cmc_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    ports:
      - "3333:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    links:
      - postgres
    depends_on:
      - postgres
    networks:
      - cmc_network

  redis:
    image: redis:latest
    hostname: cache_redis
    restart: unless-stopped
    networks:
      - cmc_network

  web_cmc:
    <<: *function
    hostname: web-cmc
    ports:
      - "8000:8000"
    command: [ "./wait-for-it.sh", "postgres:5432", "--",
               "python", "manage.py", "runserver",
               "0.0.0.0:8000" ]

    depends_on:
      - redis
      - postgres


  worker:
    <<: *function
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    links:
      - redis
    depends_on:
      - redis

  worker2:
    <<: *function
    hostname: worker2
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    links:
      - redis
    depends_on:
      - redis

  celery-beat:
    <<: *function
    hostname: worker2
    entrypoint: celery
    command: -A celery_app.app beat --loglevel=info
    links:
      - redis
    depends_on:
      - redis

  flower:
    <<: *function
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    links:
      - redis
      - worker
    depends_on:
      - redis
      - worker
    ports:
      - "5555:5555"

volumes:
  postgres_data:
    driver: local

networks:
  cmc_network:
    driver: bridge
