version: '3.1'

services:
  web_cmc:
    build:
      context: .
    environment:
      - DB_HOST=postgres
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
    ports:
      - "8000:8000"
    volumes:
      - .:/cmc
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
#    command:
#      - python manage.py runserver 0.0.0.0:8000
    depends_on:
       - postgres
       - redis

  postgres:
    container_name: postgres
    image: postgres:15.1
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped

  redis:
    image: redis:latest
    hostname: cache_redis
    restart: unless-stopped


  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - .:/cmc
    labels:
      - redis
    depends_on:
      - redis
    environment:
      - DB_HOST=postgres
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}

  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - .:/cmc
    labels:
      - redis
      - worker
    depends_on:
      - redis
      - worker
    ports:
      - "5555:5555"
